language: java

notification:
  email:
    on_success: never
    on_failure: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8eed86a6ecffb667b819
    on_success: never
    on_failure: never
    on_start: false

install: true
before_script:
  - mkdir -p travis/tmp
  - echo "wayang.basic.tempdir = file://$(pwd)/travis/tmp" >> travis/wayang.properties
  - echo "spark.driver.host = localhost" >> travis/wayang.properties
  - echo "spark.master = local[1]" >> travis/wayang.properties
  - echo "wayang.giraph.job.tracker = localhost:50300" >> travis/wayang.properties
  - echo "wayang.giraph.maxWorkers = 1" >> travis/wayang.properties
  - echo "wayang.giraph.minWorkers = 1" >> travis/wayang.properties
  - echo "wayang.mapreduce.job.counters.limit = 200" >> travis/wayang.properties
  - cat travis/wayang.properties
  - mvn_opts=("-Dorg.slf4j.simpleLogger.defaultLogLevel=error" "-Dwayang.configuration=file://$(pwd)/travis/wayang.properties")
script:
  - bin/change-scala-version.sh 2.11.8 && mvn clean install -Pdistro "${mvn_opts[@]}"

